CREATE TABLE PRODUCTOS (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    precio_unitario NUMBER(8,2),
    stock NUMBER
);

CREATE TABLE USUARIOS (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    rol VARCHAR2(50)
);

CREATE TABLE VENTAS (
    id_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto NUMBER,
    cantidad NUMBER,
    fecha DATE,
    CONSTRAINT fk_producto FOREIGN KEY (id_producto) REFERENCES PRODUCTOS(id_producto)
);


    DBMS_OUTPUT.PUT_LINE('Total de ventas para ' || TO_CHAR(p_fecha, 'DD-MM-YYYY') || ': ' || total);
END;
/
