CREATE OR REPLACE FUNCTION fn_producto_nombre(p_id IN NUMBER) RETURN VARCHAR2 IS
  v VARCHAR2(255);
BEGIN
  SELECT nombre INTO v FROM productos WHERE id = p_id;
  RETURN v;
EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL; END;
/
