CREATE OR REPLACE FUNCTION fn_precio_producto(p_id IN NUMBER) RETURN NUMBER IS
  v NUMBER;
BEGIN
  SELECT precio INTO v FROM productos WHERE id = p_id;
  RETURN v;
EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL; END;
/
